baseURL = 'https://ygg01.github.io/blog/'
title = "Ygg's horrible unsingable blog"
theme = "hugo-bearblog"
ignoreLogs = ['warning-goldmark-raw-html']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[[module.imports]]
path = 'github.com/KKKZOZ/hugo-admonitions'

[markup]
  [markup.highlight]
   style = 'base16-snazzy'
   linenos  = true
   lineNoStart = 1
